from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

class Clipboards(models.Model):
  id = models.IntegerField(primary_key=True, auto_created=True, unique=True)
  ui = models.CharField(max_length=255)#primary_key=True, max_length=255, unique=True)                           #autogenerated
  user_id = models.IntegerField(default=0)                    #for later use
  passcode = models.CharField(max_length=30)                      #for later use
  passcode_hint = models.CharField(max_length=255)                #for later use
  content = models.TextField()                                    #user generated
  times_viewed = models.IntegerField(default=0)    #start at zero
  date_created = models.DateTimeField(auto_now=True)                      #auto generated
  minutes_until_expired = models.IntegerField(default=1440, validators=[MinValueValidator(1), MaxValueValidator(525600)])
