# Generated by Django 4.1.3 on 2022-12-04 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboards',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ui', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('passcode', models.CharField(max_length=30)),
                ('passcode_hint', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('times_viewed', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('minutes_until_expired', models.IntegerField(default=1440, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(525600)])),
            ],
        ),
    ]
